<?php

namespace Lkt\Commander\Console\Commands;

use Lkt\Commander\Commander;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MakeCrontabCommand extends Command
{
    protected static $defaultName = 'lkt:make:crontab';

    protected function configure()
    {
        $this
            // the short description shown while running "php bin/console list"
            ->setDescription('Automatically generates a fresh crontab file')

            // the full command description shown when running the command with
            // the "--help" option
            ->setHelp('')
        ;
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {

        $data = Commander::getCrontabConfig();
        $data = ["# File autogenerated with lkt:make:crontab", ...$data, "\n\n"];

        file_put_contents('cron.jobs', implode("\n\n", $data));

        shell_exec('crontab < cron.jobs');
        unlink('cron.jobs');

        return 1;
    }
}